---
- name: update and install prometheus
  become: yes
  apt:
    name: prometheus
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: prometheus args
  become: yes
  template:
    src: prometheus.j2
    dest: "{{ prometheus_default }}"
    mode: 0644
    owner: root
    group: root

- name: prometheus configuration file
  become: yes
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus

- name: start prometheus
  become: yes
  systemd:
    name: prometheus
    state: started
    enabled: yes